version: 2.1

executors:
  my_executor:
    docker:
      - image: circleci/ruby:2.4.1

jobs:
  test_job:
    executor: my_executor
    steps:
      - run:
          name: test_job
          command: echo test_job
  master_job:
    executor: my_executor
    steps:
      - run:
          name: master_job
          command: echo master_job
  release_job:
    executor: my_executor
    steps:
      - run:
          name: release_job
          command: echo release_job
  tag_job:
    executor: my_executor
    steps:
      - run:
          name: tag_job
          command: echo tag_job

workflows:
  workflow:
    jobs:
      - test_job
      - master_job:
          filters:
            branches:
              only:
                - master
      - release_job:
          filters:
            branches:
              only:
                - release
      - tag_job:
          filters:
            tags:
              only: /.*/