version: 2.1

executors:
  my_executor:
    docker:
      - image: circleci/ruby:2.4.1

jobs:
  test_job:
    executor: my_executor
    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: test_job
          command: |
            echo test_job
      - run:
          name: git-pr-release
          command: |
            TMP=`curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PULL_REQUEST##*/}`
            echo $TMP
            DIST_BRANCH=`curl -H 'Authorization: token ${GITHUB_TOKEN}' https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PULL_REQUEST##*/} | jq -r '.base.ref'`
            echo ${DIST_BRANCH}
            echo ${CIRCLE_BRANCH}
            if [[ "${DIST_BRANCH:-undefined}" = "release" ]] && [[ "${CIRCLE_BRANCH:-undefined}" = "master" ]]; then
              GIT_PR_RELEASE_TOKEN=${GITHUB_TOKEN} GIT_PR_RELEASE_BRANCH_PRODUCTION=release GIT_PR_RELEASE_BRANCH_STAGING=master bundle exec git-pr-release
            fi

  master_job:
    executor: my_executor
    steps:
      - run:
          name: master_job
          command: |
            echo master_job

  release_job:
    executor: my_executor
    steps:
      - run:
          name: release_job
          command: echo release_job

  tag_job:
    executor: my_executor
    steps:
      - run:
          name: tag_job
          command: echo tag_job

workflows:
  version: 2
  workflow:
    jobs:
      - test_job
      - master_job:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
      - release_job:
          filters:
            branches:
              only:
                - release
      - tag_job:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
